import { and, asc, desc, eq, gt } from "drizzle-orm";
import { getDb } from "@/db";
import { claims, evidence, literatureCache, researchRuns, stageResults } from "@/db/schema";
import { ApiError, parseJson } from "./api-helpers";
import { getProvider, ProviderError, type ProviderResponse } from "./providers";
import type { ModelRef, ProblemSpec, RunProfile, StageId, StageOutput } from "./research-types";
import { stageIds } from "./research-types";
import { getOwnedProject, getOwnedRun, serializeProject } from "./repository";
import { stageInput, stageInstructions } from "./stage-prompts";
import { runCombinatoricsExperiment } from "./tools/combinatorics";
import { searchLiterature } from "./tools/literature";

const PROMPT_VERSION="lemma-v1";
async function collectContext(runId:string){const rows=await getDb().select().from(stageResults).where(and(eq(stageResults.runId,runId),eq(stageResults.status,"completed"))).orderBy(asc(stageResults.createdAt));return rows.filter((r)=>!r.isDeepPass&&r.outputJson).map((r)=>({stage:r.stage,output:parseJson<StageOutput>(r.outputJson!,{summary:"",claims:[],artifacts:[],openQuestions:[],suggestedNextSteps:[]})}))}
async function cachedLiterature(problem:ProblemSpec){const query=`${problem.title} ${problem.statement.slice(0,400)}`,queryKey=query.toLowerCase().replace(/\s+/g," ").trim();const [cached]=await getDb().select().from(literatureCache).where(and(eq(literatureCache.queryKey,queryKey),gt(literatureCache.expiresAt,Date.now()))).limit(1);if(cached)return parseJson(cached.resultsJson,[]);const results=await searchLiterature(query,process.env.CROSSREF_MAILTO,12);const now=Date.now();await getDb().insert(literatureCache).values({id:crypto.randomUUID(),queryKey,resultsJson:JSON.stringify(results),createdAt:now,expiresAt:now+7*24*60*60*1000}).onConflictDoUpdate({target:literatureCache.queryKey,set:{resultsJson:JSON.stringify(results),createdAt:now,expiresAt:now+7*24*60*60*1000}});return results}
async function stageTools(stage:StageId,problem:ProblemSpec){if(stage!=="evidence")return[];const [literature,experiment]=await Promise.all([cachedLiterature(problem).catch((error)=>({error:error instanceof Error?error.message:"Literature search failed"})),Promise.resolve(runCombinatoricsExperiment(problem.statement,problem.bounds.maxVertices))]);return[{name:"search_literature",output:literature},{name:"run_combinatorics_experiment",output:experiment}]}
async function normalizeClaimSupport(runId:string,output:StageOutput,tools:unknown[]):Promise<StageOutput>{const sourceIds=new Set<string>(),computationIds=new Set<string>();for(const record of tools as Array<{name?:string;output?:unknown}>){if(record.name==="search_literature"&&Array.isArray(record.output))for(const item of record.output as Array<{id?:unknown}>)if(typeof item.id==="string")sourceIds.add(item.id);if(record.name==="run_combinatorics_experiment"&&record.output&&typeof record.output==="object"&&"id" in record.output)computationIds.add(String((record.output as {id:unknown}).id))}const prior=await getDb().select({outputJson:stageResults.outputJson}).from(stageResults).where(eq(stageResults.runId,runId));for(const row of prior){if(!row.outputJson)continue;const parsed=parseJson<StageOutput|null>(row.outputJson,null);for(const artifact of parsed?.artifacts??[]){if(artifact.type==="source")sourceIds.add(artifact.id);if(artifact.type==="computation"||artifact.type==="counterexample")computationIds.add(artifact.id)}}return{...output,claims:output.claims.map((claim)=>{const valid=claim.verificationStatus==="source-supported"?claim.evidenceRefs.some((id)=>sourceIds.has(id)):claim.verificationStatus==="computation-supported"?claim.evidenceRefs.some((id)=>computationIds.has(id)):true;if(valid)return claim;return{...claim,verificationStatus:"unverified" as const,warnings:[...claim.warnings,"Downgraded by Lemma: the claimed support did not reference a recorded source or computation."]}})}}
async function persistResult(runId:string,stage:StageId,attempt:number,ref:ModelRef,result:ProviderResponse,tools:unknown[],isDeepPass=false){
  const db=getDb(),stageResultId=crypto.randomUUID(),createdAt=Date.now(),output=await normalizeClaimSupport(runId,result.output,tools);await db.insert(stageResults).values({id:stageResultId,runId,stage,attempt,provider:"openrouter",requestedModel:ref.model,returnedModel:result.returnedModel,reasoning:ref.reasoning,maxOutputTokens:ref.maxOutputTokens,status:"completed",outputJson:JSON.stringify(output),providerResponseId:result.providerResponseId,usageJson:JSON.stringify(result.usage),toolRecordsJson:JSON.stringify(tools),promptVersion:PROMPT_VERSION,isDeepPass,createdAt});
  for(const claim of output.claims){const claimId=crypto.randomUUID();await db.insert(claims).values({id:claimId,runId,stageResultId,text:claim.text,kind:claim.kind,verificationStatus:claim.verificationStatus,warningsJson:JSON.stringify(claim.warnings)});for(const refId of claim.evidenceRefs)await db.insert(evidence).values({id:crypto.randomUUID(),runId,stageResultId,claimId,type:"reference",label:refId,metadataJson:"{}"})}
  for(const artifact of output.artifacts)await db.insert(evidence).values({id:crypto.randomUUID(),runId,stageResultId,claimId:null,type:artifact.type,label:artifact.title,metadataJson:JSON.stringify({artifactId:artifact.id,...artifact.metadata})});return{stageResultId,result:{...result,output}};
}
export async function advanceRun(ownerId:string,runId:string,override?:Partial<ModelRef>){
  const run=await getOwnedRun(ownerId,runId);if(run.cancelRequested||run.status==="cancelled")throw new ApiError(409,"This run has been cancelled.");if(run.status==="completed")throw new ApiError(409,"This run is already complete.");
  const stage=stageIds[run.currentStage];if(!stage)throw new ApiError(409,"No remaining stage.");const profile=parseJson<RunProfile>(run.profileSnapshotJson,{} as RunProfile);const ref={...profile.stages[stage],...override} as ModelRef;if(!ref?.model)throw new ApiError(400,"The selected profile has no model for this stage.");
  if(run.outputTokens+ref.maxOutputTokens>profile.totalOutputLimit)throw new ApiError(409,"The run output limit would be exceeded. Increase the saved profile limit explicitly to continue.");
  const project=serializeProject(await getOwnedProject(ownerId,run.projectId));const prior=await collectContext(runId);const tools=await stageTools(stage,project);const [latest]=await getDb().select().from(stageResults).where(and(eq(stageResults.runId,runId),eq(stageResults.stage,stage))).orderBy(desc(stageResults.createdAt)).limit(1);const attempt=(latest?.attempt??0)+1;
  await getDb().update(researchRuns).set({status:"running",updatedAt:Date.now()}).where(eq(researchRuns.id,runId));
  try{const adapter=getProvider();const result=await adapter.generateStructured({model:ref.model,reasoning:ref.reasoning,maxOutputTokens:ref.maxOutputTokens,instructions:stageInstructions(stage),input:stageInput(stage,project,prior,tools)});const saved=await persistResult(runId,stage,attempt,ref,result,tools);const fresh=await getOwnedRun(ownerId,runId);const next=run.currentStage+1;const status=fresh.cancelRequested?"cancelled":next>=stageIds.length?"completed":"paused";await getDb().update(researchRuns).set({status,currentStage:next,inputTokens:fresh.inputTokens+result.usage.inputTokens,outputTokens:fresh.outputTokens+result.usage.outputTokens,reasoningTokens:fresh.reasoningTokens+result.usage.reasoningTokens,cachedTokens:fresh.cachedTokens+result.usage.cachedTokens,updatedAt:Date.now()}).where(eq(researchRuns.id,runId));return{stage,status,...saved};}
  catch(error){const detail=error instanceof ProviderError?{provider:error.provider,code:error.code,message:error.message,retryable:error.retryable}:{code:"unexpected",message:error instanceof Error?error.message:"Unexpected stage failure",retryable:false};await getDb().insert(stageResults).values({id:crypto.randomUUID(),runId,stage,attempt,provider:"openrouter",requestedModel:ref.model,reasoning:ref.reasoning,maxOutputTokens:ref.maxOutputTokens,status:"failed",usageJson:"{}",toolRecordsJson:JSON.stringify(tools),errorJson:JSON.stringify(detail),promptVersion:PROMPT_VERSION,isDeepPass:false,createdAt:Date.now()});await getDb().update(researchRuns).set({status:"failed",updatedAt:Date.now()}).where(eq(researchRuns.id,runId));throw new ApiError(error instanceof ProviderError?error.status:500,detail.message,detail)}
}
export async function deepenStage(ownerId:string,runId:string,stage:StageId,ref:ModelRef){if(stage!=="proofs"&&stage!=="critique")throw new ApiError(400,"Only proof and critique stages can receive a deep pass.");if(ref.maxOutputTokens>5000)throw new ApiError(400,"Deep passes are limited to 5,000 output tokens.");const run=await getOwnedRun(ownerId,runId);const project=serializeProject(await getOwnedProject(ownerId,run.projectId));const prior=await collectContext(runId);const tools=await stageTools(stage,project);try{const result=await getProvider().generateStructured({model:ref.model,reasoning:ref.reasoning,maxOutputTokens:ref.maxOutputTokens,instructions:`${stageInstructions(stage)}\nThis is a manually approved deep pass. Critically improve the earlier result without hiding it.`,input:stageInput(stage,project,prior,tools)});const saved=await persistResult(runId,stage,Date.now(),ref,result,tools,true);const fresh=await getOwnedRun(ownerId,runId);await getDb().update(researchRuns).set({inputTokens:fresh.inputTokens+result.usage.inputTokens,outputTokens:fresh.outputTokens+result.usage.outputTokens,reasoningTokens:fresh.reasoningTokens+result.usage.reasoningTokens,cachedTokens:fresh.cachedTokens+result.usage.cachedTokens,updatedAt:Date.now()}).where(eq(researchRuns.id,runId));return saved}catch(error){if(error instanceof ProviderError)throw new ApiError(error.status,error.message,{provider:error.provider,code:error.code,retryable:error.retryable});throw error}}
