import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { idempotencyRecords, projects, researchRuns, stageResults } from "@/db/schema";
import { ApiError, parseJson } from "./api-helpers";
import type { ProblemSpec, RunProfile, StageOutput } from "./research-types";

export function serializeProject(row:typeof projects.$inferSelect):ProblemSpec&{id:string;createdAt:number;updatedAt:number}{return{id:row.id,title:row.title,field:row.field,statement:row.statement,definitions:parseJson(row.definitionsJson,[]),assumptions:parseJson(row.assumptionsJson,[]),knownResults:parseJson(row.knownResultsJson,[]),bounds:row.boundsJson&&row.boundsJson!=="{}"?parseJson(row.boundsJson,undefined):undefined,mode:row.mode as ProblemSpec["mode"],existingProof:row.existingProof??undefined,userSources:parseJson(row.userSourcesJson,[]),createdAt:row.createdAt,updatedAt:row.updatedAt}}
export async function getOwnedProject(ownerId:string,id:string){const [row]=await getDb().select().from(projects).where(and(eq(projects.id,id),eq(projects.ownerId,ownerId))).limit(1);if(!row)throw new ApiError(404,"Research file not found.");return row}
export async function getOwnedRun(ownerId:string,id:string){const [row]=await getDb().select().from(researchRuns).where(and(eq(researchRuns.id,id),eq(researchRuns.ownerId,ownerId))).limit(1);if(!row)throw new ApiError(404,"Research run not found.");return row}
export async function getRunBundle(ownerId:string,id:string){const run=await getOwnedRun(ownerId,id);const project=await getOwnedProject(ownerId,run.projectId);const results=await getDb().select().from(stageResults).where(eq(stageResults.runId,id)).orderBy(stageResults.createdAt);return{run:{...run,profileSnapshot:parseJson<RunProfile>(run.profileSnapshotJson,{} as RunProfile)},project:serializeProject(project),results:results.map((r)=>({...r,output:r.outputJson?parseJson<StageOutput|null>(r.outputJson,null):null,usage:parseJson(r.usageJson,{}),toolRecords:parseJson(r.toolRecordsJson,[]),error:r.errorJson?parseJson(r.errorJson,null):null}))}}
export async function replayIdempotent(ownerId:string,key:string,operation:string){const [row]=await getDb().select().from(idempotencyRecords).where(and(eq(idempotencyRecords.ownerId,ownerId),eq(idempotencyRecords.key,key),eq(idempotencyRecords.operation,operation))).limit(1);return row?parseJson(row.responseJson,null):null}
export async function saveIdempotent(ownerId:string,key:string,operation:string,response:unknown){await getDb().insert(idempotencyRecords).values({id:crypto.randomUUID(),ownerId,key,operation,responseJson:JSON.stringify(response),createdAt:Date.now()});return response}
export async function listOwnedProjects(ownerId:string){const rows=await getDb().select().from(projects).where(eq(projects.ownerId,ownerId)).orderBy(desc(projects.updatedAt));return rows.map(serializeProject)}
